name: myproject
channels:
  - defaults
dependencies:
  - python=3.10
  - jupyter
  - pandas
  - geopandas
  - matplotlib
  - shapely
  - numpy
  - fiona
  - pyproj
  - rtree
  - h5py
  - pip
  - pip:
      - notebook
